apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpl
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-svc
  template:
    metadata:
      labels:
        app: nginx-svc
    spec:
      containers:
      - name: nginx-cont
        image: nginx:latest
        ports:
        - containerPort: 80
