apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dpl
  namespace: default # can using other namespace
spec:
  selector:
    matchLabels:
      app: postgres-dpl
  template:
    metadata:
      labels:
        app: postgres-dpl
    spec:
      containers:
      - name: postgres-dpl
        image: postgres:latest
        ports:
        - containerPort: 5432
        envForm:
          - configMapRef:
            name: postgres-configmap
          - secretRef:
            name: postgres-secret
