[all:vars]
ansible_user=ts
ansible_python_interpreter=/usr/bin/python3
; for first ssh, no need to answer yes no 
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[localhost]
node1 ansible_connection=local 


[agent]
node2 ansible_host=34.81.178.164 ansible_user=ts





