[all:vars]
ansible_user=ts
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[nfs-servers]
node1 ansible_host=35.229.130.158 private_ip=10.140.0.3 ansible_connection=local

[nfs-clients]
node2 ansible_host=34.81.157.91
node3 ansible_host=130.211.251.8


[all:children]
nfs-servers
nfs-clients

; ansible -i inventory.ini -m ping node1 
; ansible -i inventory.ini -m ping all 
; ansible -i inventory.ini -m command -a "uptime" all 
; ansible -i inventory.ini -m apt -a "name=nginx state=present" node2 -b