nfs_server: 
  ip: 10.140.0.3  # using internal ip

  # if we use this , it's more dynamic and more resuable
  #ip:  "{{ hostvars['localhost']['ansible_default_ipv4']['address'] }}"
  mount_path: /srv/nfs_shared
nfs_client:
  mount_path: /mnt/nfs_shared
  ips: # using internal ip
    - 10.140.0.6
    - 10.140.0.7
