[all:vars]
ansible_user=ts
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[localhost]
controller ansible_connection=local


# Dynamic load cofig here with jinja
[masters]
ts-master1 ansible_host=xxx
ts-master2 ansible_host=xxx


[workers]
ts-worker1 ansible_host=xxx
ts-worker2 ansible_host=xxx
