[localhost]
node1 ansible_connection=local

# dynamic inventory = auto config inventory based on machines that we created in gcp 

# [agents]
# node2 ansible_host=34.81.178.164 ansible_user=ts


[all:vars]
ansible_user=ts
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

