---
- name: Testing playbook
  hosts: node2
  become: true

  tasks:
    - name: Update Packages
      become: false
      ansible.builtin.apt:
        update_cache: true

    - name: Install Packages
      ansible.builtin.apt:
        name:
          - nginx
          - tree
          - 
        state: present